### PR TITLE
Updated README.md with GitHub repo stats 

### PR DESCRIPTION
**Pull request by noobrehan18**
issue #125 

added the GitHub repo stats !!!
Screenshot 2024-10-25 at 4 30 51 PM

@jindalpriyanshu101 bro pls merge it

### CODE REVIEW

**Comment by noobrehan18** [comment]
@jindalpriyanshu101 @Lokesh-Bijarniya bro pls see this pr & merge it I ve done this work but u guys re ignoring the PR's

**Comment by jindalpriyanshu101** [comment]
> @jindalpriyanshu101 @Lokesh-Bijarniya bro pls see this pr & merge it I ve done this work but u guys re ignoring the PR's

Hey @REHAN-18, PRs aren't actually getting ignored. They're just merged by @jinx-vi-0 only.

**Comment by REHAN-18** [comment]
> @jinx-vi-0

@jinx-vi-0 sir pls see this pr !!

**Comment by noobrehan18** [comment]
> > @jindalpriyanshu101 @Lokesh-Bijarniya bro pls see this pr & merge it I ve done this work but u guys re ignoring the PR's
> 
> Hey @REHAN-18, PRs aren't actually getting ignored. They're just merged by @jinx-vi-0 only.

@jinx-vi-0 sir pls see this pr !!

**Review by jindalpriyanshu101 — APPROVED** [review]

**Comment by jindalpriyanshu101** [comment]
Looks good to me!

**Pull request merged**
