### PR TITLE
New-feature-branch : Successfully pushed the full AES-256 and PBKDF2 encryption enhancements 

### PR DESCRIPTION
**Pull request by Ishratnoori**
Hi @jindalpriyanshu101 and @jinx-vi-0,

I have successfully pushed the full AES-256 and PBKDF2 encryption enhancements in the new-feature-branch. You can find the changes in the pull request I created.

Thank you for your guidance throughout this process!

Best regards,
Ishrat noori :)

### CODE REVIEW

**Comment by jindalpriyanshu101** [comment]
Well, looks like things are messed up as you kight have synced the fork before raising this PR.

I can see 517 file changes, and its next to impossible to find your actual changes in such case..

I'd recommend you to delete this branch, and redo your changes in a new up-to-dated branch. This way you'll not face any merge conflicts and it'll be easy for us to review your changes @Ishratnoori.

I appreciate your active cooperation till now ;D

**Comment by Ishratnoori** [comment]
image
Can i create a pull request? 
its displaying like CANT AUTOMATICALLY MERGE
what should i do?

**Comment by Ishratnoori** [comment]
image

**Comment by jindalpriyanshu101** [comment]
> image
> Can i create a pull request? 
> its displaying like CANT AUTOMATICALLY MERGE
> what should i do?

Yup, you should be creating a pull request only.

**Pull request closed without merging**
