### PR TITLE
Fixes : #49 Better URL Implementation

### PR DESCRIPTION
**Pull request by AskitEndo**
Worked on #49 ,
Added suggestion messages for URL format and
I updated the Toast notifications to show specific message on type of error encountered!

### CODE REVIEW

**Comment by AskitEndo** [comment]
@jindalpriyanshu101 @jinx-vi-0 Do Look on to it

**Comment by adarsh-site** [comment]
image

Showing error message here disrupts the UI and it should disappear when the field is empty.

**Comment by AskitEndo** [comment]
> image
> 
> Showing error message here disrupts the UI and it should disappear when the field is empty.

Okay will be fixed today

**Comment by AskitEndo** [comment]
@jinx-vi-0 Fixed!

**Review by adarsh-site — APPROVED** [review]

**Pull request merged**
