### PR TITLE
the bug which was causing problem while updating the data is found and resolved.

### PR DESCRIPTION
**Pull request by abhayksahu369**
#68 solved 

### backend
- in save and update password api , the password was encrypted and saved in db , but when the frontend fetched all the password, the passwords were not decrypted and hence encrypted password were shown in frontend.
- I commented down the encryption part ( I am going to raise issue about it)
### frontend
- there were some typos with id 
- I also solved some bugs present in update/save button (while updating the the button should changed to update but it was not changing sometime.
- data not updating in db is also solved 

admin I deserve more level tag even though the changes seem small but I invested huge time finding bugs.

### CODE REVIEW

**Comment by adarsh-site** [comment]
@abhayksahu369 
Please work towards resolving conflicts.

**Comment by adarsh-site** [comment]
fix merge conflicts

**Comment by abhayksahu369** [comment]
@jinx-vi-0 fixing

**Comment by abhayksahu369** [comment]
@jinx-vi-0 fixed it! merged both the code, please verify.

**Review by adarsh-site — APPROVED** [review]

**Pull request merged**
