### PR TITLE
Fixes : #26 Import Export option for passwords added

### PR DESCRIPTION
**Pull request by AskitEndo**
Worked on #26 ,
Added Button of Both Importing and Exporting the Data,
Both the functions are performed in  json data file format and can be read at backend.
Screenshot 2024-10-04 222354

All the Necessary changes are made to the Code base backend and front elements have been added with animated lordicons
Do review and merge
(This was a tough one for me 😋)

### CODE REVIEW

**Comment by AskitEndo** [comment]
@jindalpriyanshu101 @jinx-vi-0 Done 🙌🏻

**Comment by adarsh-site** [comment]
Do these changes :-
- Named them as Import, Export
- place both of them in the navbar section

and resolve conflicts.

**Comment by AskitEndo** [comment]
> Do these changes :-
> - Named them as Import, Export
> - place both of them in the navbar section
> 
> and resolve conflicts.

Okay, On it.

**Comment by AskitEndo** [comment]
> Do these changes :-
> 
> * Named them as Import, Export
> * place both of them in the navbar section
> 
> and resolve conflicts.

@jinx-vi-0  You can checkout #41 Where I implemented the changes

**Pull request closed without merging**
