### PR TITLE
Added password validation

### PR DESCRIPTION
**Pull request by kashikaga**
I have added the validation of password before saving that is now password must contain atleast 8 characters which includes capital letters,small letters, numerical values and special characters 

solves issue #7 
@jindalpriyanshu101 @jinx-vi-0 kindly check

### CODE REVIEW

**Comment by AskitEndo** [comment]
@kashikaga Nicely Done!

**Comment by adarsh-site** [comment]
@kashikaga accept username >= 3 characters.

**Review by adarsh-site — APPROVED** [review]
Great!

**Comment by kashikaga** [comment]
@jinx-vi-0 Thank you
Could you please add the label of hacktoberfest-accepted also

**Comment by adarsh-site** [comment]
@kashikaga 

Would you like to work on this follow-up issue #19  ?

**Comment by adarsh-site** [comment]
@kashikaga 
The new error message does not adhere to the color code used in the rest of the project.
image

Use same color code across the project. Below is the original one.
image

**Comment by kashikaga** [comment]
> @kashikaga
> 
> Would you like to work on this follow-up issue #19 ?

@jinx-vi-0 Yes I would like to work 
please assign me issue #19 with the labels of gssoc,hacktoberfest and level

**Comment by adarsh-site** [comment]
@kashikaga 
Okay, you can start working on it.

**Comment by kashikaga** [comment]
> @kashikaga Okay, you can start working on it.



> @kashikaga The new error message does not adhere to the color code used in the rest of the project. image
> 
> Use same color code across the project. Below is the original one. image

@jinx-vi-0 what is the issue number of this issue ?

**Comment by adarsh-site** [comment]
@kashikaga 
I have not created any issues regarding it. Please resolve it as it pertains to your previous pull request.

**Pull request merged**
