### PR TITLE
Better and responsive UI for the Homepage.

### PR DESCRIPTION
**Pull request by Ayush215mb**
I have completed the issue assigned to me #18, Please review it and accept it after adding all the labels.
Below are the Images of new UI, the footer is not visible in the ss but they are down below.
image
image

### CODE REVIEW

**Comment by adarsh-site** [comment]
hey @Ayush215mb , There is some issue with your PR. Every time a new password is generated, the page reloads, which did not happen previously.

**Comment by Ayush215mb** [comment]
I haven't changed any function syntax but still I will look into it.

**Comment by Ayush215mb** [comment]
@jinx-vi-0 check it now, I have added event.preventdefault in the generate password function which was missing before.
Now it will not get refreshed on clicking.

**Comment by Ayush215mb** [comment]
@jinx-vi-0 also don't forget to add the labels here, in the hacktober website this PR is still showing not participating so please add it before merging.
I already got my one merged PR wasted because the owner hadn't added labels so hacktober didn't count that, so please do it here before merging.

**Review by adarsh-site — APPROVED** [review]

**Comment by adarsh-site** [comment]
hey @Ayush215mb , Your pull request had several issues. I'm removing the changes for now. If you want to revisit this, please ensure that all the issues are fixed.

**Comment by Ayush215mb** [comment]
@jinx-vi-0 can you tell me the issues??

**Comment by adarsh-site** [comment]
Please review the recently closed issue. Most of the mentioned issues arose after your pull request.

**Comment by Ayush215mb** [comment]
issue #52 I can understand as I didn't checked that it was animation so i have added save icon instead of the previous one.
issue #51  is not true, after clicking on the generate password the generated password is written on the password field so anyone can write it .

**Pull request merged**
