### PR TITLE
#20  added favicon feature

### PR DESCRIPTION
**Pull request by Nimrat0199**
Solved issue :  #20  .  Made a getFavicon function which returns a url of the  favicon  . 
getFavicon function accepts domain as a parameter  .
domain could be for eg : (google.com || youtube.com || dev.to )  

Screenshot 2024-10-04 212709

### CODE REVIEW

**Comment by Nimrat0199** [comment]
the domain could also be (
https://github.com/jinx-vi-0/passop/issues 
https://www.youtube.com/results?search_query=github
https://www.youtube.com/sfdsdf)

Screenshot 2024-10-05 091850

**Review by adarsh-site — APPROVED** [review]

**Comment by Nimrat0199** [comment]
hi @jinx-vi-0  , could you please assign hacktoberfest-accepted , gssoc-ext , and a level tag

**Comment by Nimrat0199** [comment]
Thanku

**Comment by Nimrat0199** [comment]
Hi @jinx-vi-0 , could you please change the label "Level-1" to "level"  . Because of this my score on the leaderboard is 0 .

Screenshot 2024-10-06 115910

**Pull request merged**
